src/Thetjyoung.Web/Controllers/LeagueController.cs
using System;
using System.Configuration;
using System.Threading.Tasks;
using PortableLeagueAPI;
using PortableLeagueApi.Interfaces.Enums;
using System.Web.Mvc;
using Thetjyoung.Web.Models;

namespace Thetjyoung.Web.Controllers
{
    public class LeagueController : Controller
    {
        #region Constructors
        #endregion Constructors

        #region Action Methods

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> Summoner(SummonerLookupViewModel viewModel)
        {
            if (string.IsNullOrWhiteSpace(viewModel.SummonerId))
            {
                return View(viewModel);
            }
            var leagueApi = new LeagueApi(ConfigurationManager.AppSettings["LolApiKey"], RegionEnum.Na, true);
            viewModel.Summoner = await leagueApi.Summoner.GetSummonerByNameAsync(viewModel.SummonerId);

            return View(viewModel);
        }

        public ActionResult Stats()
        {
            return View();
        }

        public ActionResult Game()
        {
            return View();
        }

        #endregion ActionMethods

        #region Private Methods

        #endregion Private Methods
    }
}

src/Thetjyoung.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="Keywords" content="Thetjyoung" />
    <meta name="Description" content="About TJ" />
    <meta name="copyright" content="Copyright (c) 2014 TJ Young. All rights reserved." />
    <title>Thetjyoung (1337 Brogrammer)</title>
    <link rel="shortcut icon" href="~/favicon.png" />
    <meta name="viewport" content="width=device-width" />
    <link href="~/favicon.png" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Thetjyoung", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>

            <div class="collapse navbar-collapse" id="navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">League <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Summoner", "Summoner", "League")</li>
                            <li>@Html.ActionLink("Stats", "Stats", "League")</li>
                            <li>@Html.ActionLink("Game", "Game", "League")</li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>